"""initial schema

Revision ID: db4805f11a91
Revises: 
Create Date: 2026-04-19 02:36:32.740750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4805f11a91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidad',
    sa.Column('id_especialidad', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_especialidad')
    )
    op.create_table('estado_servicio',
    sa.Column('id_estado_servicio', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('orden_flujo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_estado_servicio')
    )
    op.create_table('prioridad',
    sa.Column('id_prioridad', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_prioridad')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_auxilio',
    sa.Column('id_tipo_auxilio', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('requiere_unidad_movil', sa.Boolean(), nullable=False),
    sa.Column('requiere_remolque', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_auxilio')
    )
    op.create_table('tipo_incidente',
    sa.Column('id_tipo_incidente', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_incidente')
    )
    op.create_table('tipo_taller',
    sa.Column('id_tipo_taller', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_taller')
    )
    op.create_table('tipo_vehiculo',
    sa.Column('id_tipo_vehiculo', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_vehiculo')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bitacora_sistema',
    sa.Column('id_bitacora', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_bitacora')
    )
    op.create_table('cliente',
    sa.Column('id_cliente', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('taller',
    sa.Column('id_taller', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('id_tipo_taller', sa.BigInteger(), nullable=False),
    sa.Column('nombre_taller', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('radio_cobertura_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_taller'], ['tipo_taller.id_tipo_taller'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_taller'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario_rol', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('id_rol', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_rol'),
    sa.UniqueConstraint('id_usuario', 'id_rol', name='uq_usuario_rol')
    )
    op.create_table('taller_auxilio',
    sa.Column('id_taller_auxilio', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('id_tipo_auxilio', sa.BigInteger(), nullable=False),
    sa.Column('precio_referencial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_tipo_auxilio'], ['tipo_auxilio.id_tipo_auxilio'], ),
    sa.PrimaryKeyConstraint('id_taller_auxilio'),
    sa.UniqueConstraint('id_taller', 'id_tipo_auxilio', name='uq_taller_tipo_auxilio')
    )
    op.create_table('taller_tipo_vehiculo',
    sa.Column('id_taller_tipo_vehiculo', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('id_tipo_vehiculo', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_tipo_vehiculo'], ['tipo_vehiculo.id_tipo_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_taller_tipo_vehiculo'),
    sa.UniqueConstraint('id_taller', 'id_tipo_vehiculo', name='uq_taller_tipo_vehiculo')
    )
    op.create_table('tecnico',
    sa.Column('id_tecnico', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('latitud_actual', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud_actual', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tecnico'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('unidad_movil',
    sa.Column('id_unidad_movil', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('tipo_unidad', sa.String(length=100), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('latitud_actual', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud_actual', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_unidad_movil'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('vehiculo',
    sa.Column('id_vehiculo', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('id_tipo_vehiculo', sa.BigInteger(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('descripcion_referencia', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_tipo_vehiculo'], ['tipo_vehiculo.id_tipo_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('incidente',
    sa.Column('id_incidente', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('id_vehiculo', sa.BigInteger(), nullable=False),
    sa.Column('id_tipo_incidente', sa.BigInteger(), nullable=False),
    sa.Column('id_prioridad', sa.BigInteger(), nullable=False),
    sa.Column('id_estado_servicio_actual', sa.BigInteger(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion_texto', sa.Text(), nullable=True),
    sa.Column('direccion_referencia', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=False),
    sa.Column('clasificacion_ia', sa.String(length=100), nullable=True),
    sa.Column('confianza_clasificacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.Column('requiere_mas_info', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_estado_servicio_actual'], ['estado_servicio.id_estado_servicio'], ),
    sa.ForeignKeyConstraint(['id_prioridad'], ['prioridad.id_prioridad'], ),
    sa.ForeignKeyConstraint(['id_tipo_incidente'], ['tipo_incidente.id_tipo_incidente'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_incidente')
    )
    op.create_table('tecnico_especialidad',
    sa.Column('id_tecnico_especialidad', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_tecnico', sa.BigInteger(), nullable=False),
    sa.Column('id_especialidad', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnico.id_tecnico'], ),
    sa.PrimaryKeyConstraint('id_tecnico_especialidad'),
    sa.UniqueConstraint('id_tecnico', 'id_especialidad', name='uq_tecnico_especialidad')
    )
    op.create_table('asignacion_servicio',
    sa.Column('id_asignacion', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('id_tecnico', sa.BigInteger(), nullable=False),
    sa.Column('id_unidad_movil', sa.BigInteger(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.Column('tiempo_estimado_min', sa.Integer(), nullable=True),
    sa.Column('estado_asignacion', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnico.id_tecnico'], ),
    sa.ForeignKeyConstraint(['id_unidad_movil'], ['unidad_movil.id_unidad_movil'], ),
    sa.PrimaryKeyConstraint('id_asignacion'),
    sa.UniqueConstraint('id_incidente')
    )
    op.create_table('calificacion_servicio',
    sa.Column('id_calificacion', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=False),
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('id_tecnico', sa.BigInteger(), nullable=True),
    sa.Column('puntuacion', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_calificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnico.id_tecnico'], ),
    sa.PrimaryKeyConstraint('id_calificacion'),
    sa.UniqueConstraint('id_incidente')
    )
    op.create_table('evidencia',
    sa.Column('id_evidencia', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=False),
    sa.Column('tipo_evidencia', sa.String(length=50), nullable=False),
    sa.Column('archivo_url', sa.String(length=500), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    op.create_table('historial_incidente',
    sa.Column('id_historial', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=False),
    sa.Column('id_estado_anterior', sa.BigInteger(), nullable=True),
    sa.Column('id_estado_nuevo', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario_actor', sa.BigInteger(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_estado_anterior'], ['estado_servicio.id_estado_servicio'], ),
    sa.ForeignKeyConstraint(['id_estado_nuevo'], ['estado_servicio.id_estado_servicio'], ),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_usuario_actor'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_table('metrica_incidente',
    sa.Column('id_metrica', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=False),
    sa.Column('tiempo_asignacion_seg', sa.Integer(), nullable=True),
    sa.Column('tiempo_llegada_seg', sa.Integer(), nullable=True),
    sa.Column('tiempo_resolucion_seg', sa.Integer(), nullable=True),
    sa.Column('cantidad_rechazos', sa.Integer(), nullable=False),
    sa.Column('fue_reasignado', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.PrimaryKeyConstraint('id_metrica'),
    sa.UniqueConstraint('id_incidente')
    )
    op.create_table('notificacion',
    sa.Column('id_notificacion', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo_notificacion', sa.String(length=50), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('pago_servicio',
    sa.Column('id_pago_servicio', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('estado_pago', sa.String(length=50), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('referencia_transaccion', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.PrimaryKeyConstraint('id_pago_servicio'),
    sa.UniqueConstraint('id_incidente')
    )
    op.create_table('solicitud_taller',
    sa.Column('id_solicitud_taller', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('distancia_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('puntaje_asignacion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado_solicitud', sa.String(length=50), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_solicitud_taller')
    )
    op.create_table('comision_plataforma',
    sa.Column('id_comision', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_pago_servicio', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto_comision', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_pago_servicio'], ['pago_servicio.id_pago_servicio'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_comision'),
    sa.UniqueConstraint('id_pago_servicio')
    )
    op.create_table('detalle_pago',
    sa.Column('id_detalle_pago', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_pago_servicio', sa.BigInteger(), nullable=False),
    sa.Column('id_taller_auxilio', sa.BigInteger(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pago_servicio'], ['pago_servicio.id_pago_servicio'], ),
    sa.ForeignKeyConstraint(['id_taller_auxilio'], ['taller_auxilio.id_taller_auxilio'], ),
    sa.PrimaryKeyConstraint('id_detalle_pago')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_pago')
    op.drop_table('comision_plataforma')
    op.drop_table('solicitud_taller')
    op.drop_table('pago_servicio')
    op.drop_table('notificacion')
    op.drop_table('metrica_incidente')
    op.drop_table('historial_incidente')
    op.drop_table('evidencia')
    op.drop_table('calificacion_servicio')
    op.drop_table('asignacion_servicio')
    op.drop_table('tecnico_especialidad')
    op.drop_table('incidente')
    op.drop_table('vehiculo')
    op.drop_table('unidad_movil')
    op.drop_table('tecnico')
    op.drop_table('taller_tipo_vehiculo')
    op.drop_table('taller_auxilio')
    op.drop_table('usuario_rol')
    op.drop_table('taller')
    op.drop_table('cliente')
    op.drop_table('bitacora_sistema')
    op.drop_table('usuario')
    op.drop_table('tipo_vehiculo')
    op.drop_table('tipo_taller')
    op.drop_table('tipo_incidente')
    op.drop_table('tipo_auxilio')
    op.drop_table('rol')
    op.drop_table('prioridad')
    op.drop_table('estado_servicio')
    op.drop_table('especialidad')
    # ### end Alembic commands ###
